version: '3.8'

services:
  backend:
    build: ./backend
    container_name: virelli_backend
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app
      - ./frontend/images/products:/app/images
    environment:
      - DATABASE_URL=sqlite:////app/virelli.db


  frontend:
    image: nginx:alpine
    container_name: virelli_frontend
    ports:
      - "80:80"  
    volumes:
      - ./frontend:/usr/share/nginx/html  